### ISSUE TITLE
Currently not usable with create-react-native-app

### ISSUE THREAD

**Issue by olsio** [yeojz/otplib#10]
I was trying to use the library in a react-native app, created by the create-react-native-app script. The problem is that this will run the app in the expo.io container which does not expose the native crypto module causing **Unable to resolve module crypto**.

As far as I can see the otplib is already doing some magic to check if this runs in browser or node to switch out the randomBytes routine's implementation. I am sure adding another detection branch for react-native/expo could enable otblib run in that environment as well by using browserfy-crypto implemenations.

I already tried to use the crypto-shim proposed for react-native but this requires the ejection of the project into a proper react-native application to link the native random bytes implementation. With this I am loosing the convenience of the expo client and libs.
https://github.com/mvayngrib/react-native-crypto

I will try to create a pull request if I find a solution but you might see an easy fix.

Attached an example project. Running it in the simulator or on an device will trigger the fault. Running it in node is fine.
[otp-crypto-test.zip](https://github.com/yeojz/otplib/files/1199833/otp-crypto-test.zip)

**Comment by yeojz** [comment]
@olsio The current browser implementation is done via Webpack by aliasing it to the custom implementation. So for browsers, you'll actually use the distribution instead of the normal files.

I think there are 2 ways of doing on top of the current system:

- add another alias and build it for react-native
- add it as an option parameter instead of importing the crypto module directly, allowing you to swap it out.

I'm actually toying with the thought of switching out the build process in the next major (6.0) release to cater for multi-packages instead. i.e. `otplib-browser`, `otplib-core`, `otplib-authenticator` which would make it easy to add `otplib-react-native` to the mix.

Let me know your thoughts.

**Comment by olsio** [comment]
I looked into the problem some more and fount that this is not really a react-native problem but with expo.io. react-native allows you to link a native randomBytes implementation and monkey patch it in but expo only allows pure JS.

In general your library requires not many crypto routines all of which are available in JS only implementations except for randomBytes but randomBytes is only required for generateSecret which could be replaced with a non-secure random fallback.

In general I would advise against split it our into more modules. If you want to avoid further dependencies you could handle that in the build process and have several build targets.

I would favour your second option. There could be a crypto shim that autodetects the environment and swaps out the implementation as needed. This would also allow the inject of a custom implementation as suggested.

I will also look into it and might be able to get you a first draft PR.

**Comment by olsio** [comment]
@yeojz I have a PR that would allow the plugging of the implementation but it does not solve my issue. I was trying to check if crypto module is available by doing a require inside of a try catch but require is also not defined in expo which causes a crash.

I don't think there is a generic solution and making the implementation pluggable has no real benefit for your project as you already cover web and node.

I think I will just fork your code and create one special custom build for my project.

**Comment by yeojz** [comment]
@olsio Alright. Sure. 

Let me know if things work well for you. 
I don't mind putting a link over to your custom build or maybe a patch description in the README if it helps others as well.

I'll go ahead and close this thread for now. Cheers.

**Comment by aldocano29** [comment]
I tried @olsio version for react native... it works well if the secret is a HEX of length 32. But if the length changes to 16, the token generated doesn't match the one generated by Google authenticator. 

I really want to use this library for my project...

**Comment by aldocano29** [comment]
In the end I used Browserify and I could use the library... a bit messy but it works

**Comment by pranshuchittora** [comment]
@aldocano29 can you pls share the steps for the same
