### ISSUE TITLE
thirty-two does not have a license. change to base32-encode/base32-decode

### ISSUE THREAD

**Issue by soldair** [yeojz/otplib#104]
**Is your feature request related to a problem? Please describe.**

thirty-two, the only dep of this package, doesn't have a license file in any version or a license field in package json. Because its not open source licensed i cant use this package =(

**Describe the solution you'd like**

i think that the recently updated and maintained base32-encode/base32-decode packages should be an adequate replacement for thirty-two. 

**Describe alternatives you've considered**

ill have to pick another library but it seems that most depend on this uses library.

I've opened an issue on the repo for thirty-two and have not heard back from the maintainer yet.

**Additional context**

if you run `npx js-green-licenses otplib` you can test to see if you depend on anything that's not licensed.

**Comment by soldair** [comment]
im investigating pr-ing this but it seems that thirty-two is exposed in some build config so its not as straight forward as just replacing the requires

**Comment by soldair** [comment]
im wrong. it has a license its just not referenced in the package.json so my tool missed it

**Comment by yeojz** [comment]
@soldair  Thanks for looking into this and bring up that issue. I'm glad the license issue is covered. 

You've brought up a good point on alternatives though. Maybe it would do for the library to be agnostic towards this dependency as well. Thanks for the heads-up on `js-green-licenses`. 

Cheers.
Gerald.

p.s. the entries in `build.config.js` is to configure `rollup` to treat it as an external dependency and not bundle thirty-two into the final build.
