### ISSUE TITLE
otplib on ios with ionic

### ISSUE THREAD

**Issue by marcosgouvea** [yeojz/otplib#115]
Hello, i'm having an issue with this lib on my ionic3 project.
For Android it builds and works perfectly, but on IOS it crash the app right after the splash screen, the screen keeps white.

that my info

`import authenticator from 'otplib/authenticator';

authenticator.options = {
          algorithm: 'sha1',
          step: 60,
          digits: 6
};
var validationCode = authenticator.generate(this.user.userSecret);`

Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.10

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 1.2.1, (and 23 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.6.0 (/usr/local/bin/node)
   npm        : 6.1.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000

my package.json
`{
  "name": "EasyChange",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/action-sheet": "^4.8.0",
    "@ionic-native/android-permissions": "^4.8.0",
    "@ionic-native/background-mode": "^4.8.0",
    "@ionic-native/barcode-scanner": "^4.8.0",
    "@ionic-native/camera": "^4.8.0",
    "@ionic-native/clipboard": "^4.8.0",
    "@ionic-native/contacts": "^4.8.0",
    "@ionic-native/core": "4.7.0",
    "@ionic-native/crop": "^4.8.0",
    "@ionic-native/device": "^4.8.0",
    "@ionic-native/facebook": "^4.8.0",
    "@ionic-native/fingerprint-aio": "^4.7.0",
    "@ionic-native/firebase": "^4.9.0",
    "@ionic-native/geolocation": "^4.8.0",
    "@ionic-native/google-plus": "^4.8.0",
    "@ionic-native/local-notifications": "^4.10.1",
    "@ionic-native/onesignal": "^4.8.0",
    "@ionic-native/sms": "^4.8.0",
    "@ionic-native/social-sharing": "^4.8.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic/pro": "1.0.20",
    "@ionic/storage": "2.1.3",
    "angular2-qrcode": "^2.0.1",
    "angularfire2": "^5.0.0-rc.11",
    "brmasker-ionic-3": "^1.1.0",
    "cordova-android": "^7.0.0",
    "cordova-clipboard": "^1.2.1",
    "cordova-ios": "4.5.5",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-add-swift-support": "^1.7.2",
    "cordova-plugin-android-permissions": "^1.0.0",
    "cordova-plugin-background-mode": "^0.7.2",
    "cordova-plugin-badge": "^0.8.7",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-facebook4": "^2.3.0",
    "cordova-plugin-fingerprint-aio": "^1.3.8",
    "cordova-plugin-firebase": "^1.1.0",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googleplus": "^5.3.0",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^1.2.1",
    "cordova-plugin-local-notification": "^0.9.0-beta.2",
    "cordova-plugin-sms": "^1.0.5",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "git+https://github.com/apache/cordova-plugin-statusbar.git",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.1",
    "cordova-sms-plugin": "^0.1.13",
    "es6-promise-plugin": "^4.2.2",
    "firebase": "^5.1.0",
    "hi-base32": "^0.5.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "minimist": "^1.2.0",
    "moment": "^2.22.2",
    "onesignal-cordova-plugin": "^2.4.3",
    "otplib": "^10.0.0",
    "phonegap-plugin-barcodescanner": "^8.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-camera": {},
      "onesignal-cordova-plugin": {},
      "cordova-plugin-background-mode": {},
      "cordova-plugin-android-permissions": {},
      "cordova-clipboard": {},
      "cordova-plugin-actionsheet": {},
      "cordova-plugin-contacts": {},
      "cordova-plugin-crop": {},
      "cordova-plugin-device": {},
      "cordova-plugin-facebook4": {
        "APP_ID": "",
        "APP_NAME": "",
        "ANDROID_SDK_VERSION": "4.+"
      },
      "cordova-plugin-x-socialsharing": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To locate you"
      },
      "cordova-plugin-googleplus": {
        "REVERSED_CLIENT_ID": ""
      },
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-firebase": {},
      "cordova-plugin-fingerprint-aio": {
        "FACEID_USAGE_DESCRIPTION": " "
      },
      "cordova-sms-plugin": {},
      "cordova-plugin-sms": {},
      "cordova-plugin-local-notification": {},
      "cordova-plugin-statusbar": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}`

![screen shot 2018-08-30 at 14 40 51](https://user-images.githubusercontent.com/12238079/44873353-5bb88700-ac6e-11e8-8a81-7400bf22f4ae.png)
![whatsapp image 2018-08-30 at 14 42 05](https://user-images.githubusercontent.com/12238079/44873423-902c4300-ac6e-11e8-87de-d9abde4cb32c.jpeg)

**Comment by yeojz** [comment]
Can you see where the syntax error is located?

It seems like a general error where `const` is not supported on that version of iOS and not just specific to the library.  Android works because `const` and `let` are probably supported.

Do you have any code transpiler in your build process?

**Comment by yeojz** [comment]
@marcosgouvea what's your iOS version?

**Comment by marcosgouvea** [comment]
the ipad im working have ios 9.3.5 
and my computer is macOs high sierra 10.13.6

**Comment by marcosgouvea** [comment]
i just tested in another devices, and in ios 11 it works

**Comment by yeojz** [comment]
@marcosgouvea 
for ios 9.3.5, can you try installing the beta? i.e. `npm install otplib@next --save`

Thanks

**Comment by marcosgouvea** [comment]
Wow ! worked like a charm ! thank you so much 


![whatsapp image 2018-09-04 at 11 42 03](https://user-images.githubusercontent.com/12238079/45038511-b9b2e900-b037-11e8-97f1-38faec2a5e7f.jpeg)

**Comment by yeojz** [comment]
released in v10.2.2
