### ISSUE TITLE
authenticator.keyuri does not uri encode user and service

### ISSUE THREAD

**Issue by tobdub** [yeojz/otplib#126]
**Describe the bug**
keyuri should probably uri encode user and service to allow spaces etc, although this would be a breaking change. Or at least mention in the documentation that uri encoding is needed.

**To Reproduce**
otplib.authenticator.keyuri("{secret}", "acme co", "JBSWY3DPEHPK3PXP")

**Comment by yeojz** [comment]
Thanks for the feedback @tobdub 

Will add in to the documentation for the next minor release,
and have it encoded in the next major release.

**Comment by yeojz** [comment]
released in https://github.com/yeojz/otplib/releases/tag/v11.0.0
