### ISSUE TITLE
Not working on expo.io react native app

### ISSUE THREAD

**Issue by matthewsuan** [yeojz/otplib#149]
**Describe the bug**
Module crpyto not found when used in expo.io

**To Reproduce**
1. Install expo
2. expo init Project
3. Edit App.js and paste code below
```
import otplib from 'otplib'

const secret = 'KVKFKRCPNZQUYMLXOVYDSQKJKZDTSRLD'
const token = otplib.generate(secret) // 556443
``

**Expected behavior**
Should not have errors

**Environment (please provide any relevant information):**
 - OS: MacOs Mojave
 - Node / Yarn: node8.6
 - Any frameworks: Expo/React Native

**Comment by yeojz** [comment]
hi @matthewsuan 

It would seem like `expo.io` does not allow the use of `crypto`
ref: https://forums.expo.io/t/how-can-i-get-access-to-crypto-is-it-possible-to-use-rn-nodeify/2348

you'll need to provide a expo.io friendly crypto version.

eg:
```js
import authenticator from 'otplib/authenticator';

authenticator.options = { 
    crypto: {
        createHmac: () => {},
        randomBytes: () => {},
    };
};

const secret = 'KVKFKRCPNZQUYMLXOVYDSQKJKZDTSRLD'
const token = authenticator.generate(secret);
```

**Comment by matthewsuan** [comment]
thanks @yeojz 

I also looked into crypto js and it seems there are functions over there I can use for this.

Just wondering though if you have tried using crypto js for this?

Ty

**Comment by yeojz** [comment]
@matthewsuan 
I have not worked on any expo.io projects and as such haven't personally tested it on the platform.

That said, I whipped up a sample replacement using `crypto-js`
https://github.com/yeojz/otplib/tree/feat-cryptojs-sample/packages/otplib-cryptojs

I have not tested it exhaustively, but it might be a possible solution.

**Comment by matthewsuan** [comment]
thanks @yeojz i will look into it and will update this issue afterwards.

I appreciate your time on this.

**Comment by matthewsuan** [comment]
This is already fixed. the solution from @yeojz works great. Ty

**Comment by CarlAmbroselli** [comment]
I just had the same issue. Please note that if you are using crypto-js in your expo app that you will also need to use crypto-js in your backend, until https://github.com/brix/crypto-js/issues/220 is resolved.

**Comment by pranshuchittora** [comment]
@matthewsuan how to use this -> https://github.com/yeojz/otplib/tree/feat-cryptojs-sample/packages/otplib-cryptojs
