### ISSUE TITLE
Token by time and number of times viewed

### ISSUE THREAD

**Issue by slmarcos** [yeojz/otplib#151]
Hello, how can I implement a valid token by time and number of times viewed?

Tnks

**Comment by yeojz** [comment]
Can you elaborate your scenario?

**Comment by slmarcos** [comment]
> Can you elaborate your scenario?

I need to generate a token that has validity of X days for the user and if used within the stipulated period is invalidated after use.

**Comment by yeojz** [comment]
You can use `step` option (https://github.com/yeojz/otplib#available-options) to set the number of days (in seconds) of validity.

As for invalidation after use, you'll need to implement that outside of the library. 
For example, you could add it to a redis store on generation and removing it either on expiry or when it is used.
