### ISSUE TITLE
Question: Why can't totp.check be used with tokens generated from a authenticator.generateSecret?

### ISSUE THREAD

**Issue by Bhargee** [yeojz/otplib#155]
What is different about those two algorithms? I thought Google authenticator implemented stock TOTP?

**Comment by yeojz** [comment]
Ultimately, Google Authenticator is using TOTP at its core. 
The differences comes in the form of expected inputs / configuration.

- Key encoding:
   - TOTP: `ascii`
   - Authenticator: `hex`

- Authenticator expects the hex key to be base32 encoded. No requirements for TOTP.
