### ISSUE TITLE
Who don't the classes accept the options object?

### ISSUE THREAD

**Issue by CheyenneForbes** [yeojz/otplib#156]
Who don't the classes accept a options object? 

Instead of 
```
const totp = new otplib.TOTP();
totp.options = {
  /*props*/\
}
```
I'd like to do:
```
const totp = new otplib.TOTP({/*props*/});
```

**Comment by yeojz** [comment]
Yes. It could.

At the time of first writing, I didn't think it was necessary since I assumed most users would go with `otplib.totp.METHOD` and very rarely would instantiate a new class instance.
