### ISSUE TITLE
window is not defined with mocha, jsdom, and enzyme

### ISSUE THREAD

**Issue by ricick** [yeojz/otplib#158]
**Describe the bug**
I'm having problems getting this library to work with mocha/enzyme tests. 

It seems no matter what i do to try and set up jsdom to provide the window object before this library is imported I get `ReferenceError: window is not defined`

I'm following the guide here:
https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

Any pointers would be appreciated.

**To Reproduce**
1. create a mocha/enzyme test project that uses jsdom to create the window object
2. import otplib from 'otplib/otplib-browser' in your code

**Comment by yeojz** [comment]
@ricick 
possible to have a demo repository or codesandbox? 

Also, if you are using a bundler, you might want to do `import otplib from 'otplib'` instead.

**Comment by ricick** [comment]
Hey. I got around it by using otplib and importing crypto myself. I assumed from the docs that I had to use the browser bundled version even though i'm using webpack etc.
