### ISSUE TITLE
Digits sometimes returning wrong length

### ISSUE THREAD

**Issue by aurbina83** [yeojz/otplib#164]
**Describe the bug**
With 
```
authenticator.options = {
  digits: 6
};
```
I will sometimes get back 5 digits in length of a code, suggesting that codes might be getting generated with a leading 0. `023432`

Whenever I verify 5 digit codes, they fail to verify.

**Environment (please provide any relevant information):**
 - OS: MacOS 12.14.4
 - Browser:
 - Node / Yarn: 11.13.0
 - Any frameworks:

**Additional context**

**Comment by yeojz** [comment]
Hi @aurbina83

From the code, the values are actually converted to strings and left padded with 0.
Might it be possible that the values were converted to integers after generation?

If you have a sample code that you see the issue, it would help greatly with debugging.

Thanks!

**Comment by aurbina83** [comment]
You were right @yeojz, this can probably be closed!
