### ISSUE TITLE
Google authenticator token won't match

### ISSUE THREAD

**Issue by pavles6** [yeojz/otplib#167]
I cannot realize what could be problem. I have read docs couple of times but it still throws false from authenticator.verify()

// foundUser is fetched user from DB

Token provider func:
```
const secret = otplib.authenticator.generate();

    foundUser.secret = secret;
    await foundUser.save();

    const otpauth = otplib.authenticator.keyuri(
      foundUser.email,
      "Remind Me",
      secret
    );
    const qrCode = await QR.toDataURL(otpauth);

    if (qrCode) {
      console.log(qrCode);
      return {
        qrCodeUri: qrCode
      };
    }
```

Token validator:
```
  console.log(`Expected: ${otplib.authenticator.generate(foundUser.secret)}`);
  console.log(`User: ${userToken}`);
  
const verified = otplib.authenticator.verify({
    token: userToken,
    secret: foundUser.secret
  });

  if (verified) {
    const token = jwt.sign(
      {
        email,
        username: foundUser.username
      },
      jwt_secret
    );
    return {
      token
```
    };

**Comment by UziTech** [comment]
What are the options you pass to `otplib.authenticator.options`?

It could be an issue with the keyuri not including all of the parameters https://github.com/yeojz/otplib/issues/166#issuecomment-515037694

**Comment by yeojz** [comment]
- As mentioned above, if you have set your algorithms to anything other than SHA1, it is not going to work with Google Authenticator.

- I'm assuming you are using v11? If not try the latest stable or beta versions.
  - `npm install otplib`
  - `npm install otplib@next`

Do reopen this issue if you are still encountering problems. Thanks
