### ISSUE TITLE
Invalid 2FA Code, only when tests are ran on Mac Mini server.

### ISSUE THREAD

**Issue by George-BC** [yeojz/otplib#193]
**Describe the bug**
I use this library for 2FA in my automated tests.  The application is stored on our own server (Mac Mini) and uses BrowserStack to run the tests, the 2FA code is always invalid. 

**Expected behavior**
2FA code  to be valid. If I run the them locally or on the cloud via my machine, 2FA always works.

**Additional context**
I understand this is a very niche issue. A point in the right direction would be much appreciated. Some code below:

```
const otplib = require('otplib');

const secret = "secret here"; 

module.exports.generate2FACode = function() {
    return otplib.authenticator.generate(secret);
}

```

```
async enterTwoFactorCode () {
        try {
            const element = await this.findE2eElement("twoFactorCodeInput");
            await this.focusOnElement(element);
            await element.clear();
            await element.sendKeys(twoFactorAuth.generate2FACode());
        } catch (error) {
            await this.logFailure();
            assert.fail("Unable to enter Two Factor code.");
        }
    }

```

**Comment by yeojz** [comment]
@George-BC 
Just getting the usual first culprit out of the way:
Is the clock on the mac mini and browserstack showing correct time? 
Since it is time based, the generated code will differ.

**Comment by George-BC** [comment]
@yeojz I will look into this and get back to you in next day or so, thanks!

**Comment by George-BC** [comment]
@yeojz The Mac Mini was 3 minutes behind, changing it fixed the issue. Thanks for the help!
