### ISSUE TITLE
how do I get 16 secret key?

### ISSUE THREAD

**Issue by inakarune** [yeojz/otplib#194]
hello.
I wonder how to get secret key.
I saw demo secret on your demo site.
I want it as follow.

WNSI7324JNTARPQF

somebody help me!

**Comment by dunghoangpg** [comment]
Did you have solution for it? @inakarune ??

**Comment by vafada** [comment]
same question i have... @inakarune how did you fix it.

Currently calling `generateSecret()` for me returns a random length string for every call
