### ISSUE TITLE
Publish Library for Polymer Components

### ISSUE THREAD

**Issue by Exnadella** [yeojz/otplib#196]
Hello Team,

Could you please publish the OTPLIB to support the PWA Polymer Web components, this would enable the community to integrate HOTP using WEB Components.  The Web components are Java Script files, needed to publish them in ES5, ES6, ES Modules to AMD Modules.

https://polymer-library.polymer-project.org/3.0/docs/tools/documentation

**Below are the list of polymer Elements published by Polymer Team.**
https://github.com/PolymerElements/app-layout
https://github.com/PolymerElements/app-localize-behavior
https://github.com/PolymerElements/app-media
https://github.com/PolymerElements/app-route
https://github.com/PolymerElements/app-storage
https://github.com/PolymerElements/font-roboto
https://github.com/PolymerElements/font-roboto-local
https://github.com/PolymerElements/gold-cc-cvc-input
https://github.com/PolymerElements/gold-cc-expiration-input
https://github.com/PolymerElements/gold-cc-input
https://github.com/PolymerElements/gold-phone-input
https://github.com/PolymerElements/gold-zip-input
https://github.com/PolymerElements/iron-a11y-announcer
https://github.com/PolymerElements/iron-a11y-keys
https://github.com/PolymerElements/iron-a11y-keys-behavior
https://github.com/PolymerElements/iron-ajax
https://github.com/PolymerElements/iron-autogrow-textarea
https://github.com/PolymerElements/iron-behaviors
https://github.com/PolymerElements/iron-checked-element-behavior
https://github.com/PolymerElements/iron-collapse
https://github.com/PolymerElements/iron-component-page
https://github.com/PolymerElements/iron-demo-helpers
https://github.com/PolymerElements/iron-doc-viewer
https://github.com/PolymerElements/iron-dropdown
https://github.com/PolymerElements/iron-fit-behavior
https://github.com/PolymerElements/iron-flex-layout
https://github.com/PolymerElements/iron-form
https://github.com/PolymerElements/iron-form-element-behavior
https://github.com/PolymerElements/iron-icon
https://github.com/PolymerElements/iron-icons
https://github.com/PolymerElements/iron-iconset
https://github.com/PolymerElements/iron-iconset-svg
https://github.com/PolymerElements/iron-image
https://github.com/PolymerElements/iron-input
https://github.com/PolymerElements/iron-jsonp-library
https://github.com/PolymerElements/iron-label
https://github.com/PolymerElements/iron-list
https://github.com/PolymerElements/iron-localstorage
https://github.com/PolymerElements/iron-location
https://github.com/PolymerElements/iron-media-query
https://github.com/PolymerElements/iron-menu-behavior
https://github.com/PolymerElements/iron-meta
https://github.com/PolymerElements/iron-overlay-behavior
https://github.com/PolymerElements/iron-pages
https://github.com/PolymerElements/iron-range-behavior
https://github.com/PolymerElements/iron-resizable-behavior
https://github.com/PolymerElements/iron-scroll-target-behavior
https://github.com/PolymerElements/iron-scroll-threshold
https://github.com/PolymerElements/iron-selector
https://github.com/PolymerElements/iron-swipeable-container
https://github.com/PolymerElements/iron-test-helpers
https://github.com/PolymerElements/iron-validatable-behavior
https://github.com/PolymerElements/iron-validator-behavior
https://github.com/PolymerElements/marked-element
https://github.com/PolymerElements/neon-animation
https://github.com/PolymerElements/paper-badge
https://github.com/PolymerElements/paper-behaviors
https://github.com/PolymerElements/paper-button
https://github.com/PolymerElements/paper-card
https://github.com/PolymerElements/paper-checkbox
https://github.com/PolymerElements/paper-dialog
https://github.com/PolymerElements/paper-dialog-behavior
https://github.com/PolymerElements/paper-dialog-scrollable
https://github.com/PolymerElements/paper-drawer-panel
https://github.com/PolymerElements/paper-dropdown-menu
https://github.com/PolymerElements/paper-fab
https://github.com/PolymerElements/paper-header-panel
https://github.com/PolymerElements/paper-icon-button
https://github.com/PolymerElements/paper-input
https://github.com/PolymerElements/paper-item
https://github.com/PolymerElements/paper-listbox
https://github.com/PolymerElements/paper-material
https://github.com/PolymerElements/paper-menu-button
https://github.com/PolymerElements/paper-progress
https://github.com/PolymerElements/paper-radio-button
https://github.com/PolymerElements/paper-radio-group
https://github.com/PolymerElements/paper-ripple
https://github.com/PolymerElements/paper-scroll-header-panel
https://github.com/PolymerElements/paper-slider
https://github.com/PolymerElements/paper-spinner
https://github.com/PolymerElements/paper-styles
https://github.com/PolymerElements/paper-swatch-picker
https://github.com/PolymerElements/paper-tabs
https://github.com/PolymerElements/paper-toast
https://github.com/PolymerElements/paper-toggle-button
https://github.com/PolymerElements/paper-toolbar
https://github.com/PolymerElements/paper-tooltip
https://github.com/PolymerElements/prism-element
https://github.com/PolymerElements/test-fixture

Thanks,
Ranganath.

**Comment by yeojz** [comment]
@Exnadella what sort of OTP component and behaviour are you looking at?

Most of the OTP logic should be placed server side, while the UI only has an input which is subsequently sent to the server for validation.

**Comment by Exnadella** [comment]
Thanks for quick response.  We need a component which can be connected to the back end and validate the OTP.  
The component should be flexible to integrate or call any where in the code to validate and raise the OTP as required.  
A confirm message that OTP is valid.
The component should be flexible and valid for a certain duration of time 0-60 minutes.

**Comment by yeojz** [comment]
The expected coverage of the component is out of scope and is very UI specific.
As you have mentioned, the code to validate is elsewhere and is not in this component. 

It would be better placed for it to be as part of a UI component library separate from this repository.

**Comment by Exnadella** [comment]
The Web Components published in Polymer are accepted in all Browsers.  If we have the front end component in polymer we should be able to integrate to back end to validate the code via API.  We can support in developing the custom component for front end if required, we don't know about back end functionality.

**Comment by yeojz** [comment]
@Exnadella I understand what you're proposing and I do agree it is great to have a drop-in component tailored for OTP.

However this repository is more concerned with OTP validation and generation logic. i.e. your API / backend. Thus, having UI components (like input / confirmation messages) is really out-of-scope for this project. 

Furthermore, you might not need an entirely new library. Can consider using https://www.webcomponents.org/element/@polymer/iron-input and define a custom `Polymer.IronValidatorBehavior` that calls the validation api.
