### ISSUE TITLE
Any Example for NodeJS

### ISSUE THREAD

**Issue by zohaib-novaturesol** [yeojz/otplib#208]
Hi
I want to use this lib in my node js project but there is no documentation for node js. The way is described is for typescript and I am not using typescript. When I try to use it according to node, I got error

`const authenticator = require('otplib');`
` const secret = 'KVKFKRCPNZQUYMLXOVYDSQKJKZDTSRLD';`
` const token = authenticator.generate(secret);`

Getting Error:   authenticator.generate is not a function

@yeojz @UziTech @madarche @encX @olsio

**Comment by yeojz** [comment]
hi @zohaib-novaturesol 

Try the following:

```js
const otplib = require('otplib');
const secret = 'KVKFKRCPNZQUYMLXOVYDSQKJKZDTSRLD';
const token = otplib.authenticator.generate(secret);
```

Examples are still for node.js, and not typescript,  It's written using the `import` syntax of the future javascript standard.

p.s. Do avoid tagging all contributors.

**Comment by zohaib-novaturesol** [comment]
Thanks...!!
It worked for me.
