### ISSUE TITLE
Receiving a 404 when trying to access the API documentation

### ISSUE THREAD

**Issue by lfarrel6** [yeojz/otplib#289]
**Describe the bug**
Receiving a 404 when attempting to access [the API documentation](https://otplib.yeojz.dev/api)

**To Reproduce**
1. Go to [the API docs](https://otplib.yeojz.dev/api)

**Expected behavior**
Visible API documentation

**Screenshots**
![404 screen](https://user-images.githubusercontent.com/17024284/79328780-82dcce80-7f0e-11ea-9905-d5c81dfa8779.png)

**Comment by PJijin** [comment]
Hey, have you got the docs page?

**Comment by intensite** [comment]
As of 2020-07-29 the problem is still there

![image](https://user-images.githubusercontent.com/7981384/88840184-17132e80-d1aa-11ea-9f8b-3d12d54744bc.png)
