### ISSUE TITLE
[feature] use a users time based token to derive secret key

### ISSUE THREAD

**Issue by SilentCicero** [yeojz/otplib#304]
I'd like to use this library kind of in reverse. 

Could this library be used such that the secret token is somehow derivable given a users time based token?

I know this seems odd, but it would have some really interesting properties cryptographically, especially when regenerating a key from the app.

**Comment by Signus** [comment]
Given the use of HMAC in both RFC 4226 and 6238, you're really talking about the reversal of a hash function based on a given token and time to derive the secret token. This isn't a feature ask, it's asking to break the foundations of H/TOTP and what makes those algorithms widely usable and trusted for 2FA.

**Comment by SilentCicero** [comment]
Yeah after reading closer into the scheme and what HMAC was I realized the
tokens are just an alignment check between a shared key.

I didn’t do enough reading, apologies, we can close this.
