### ISSUE TITLE
6 digit authenticator token is not working with Microsoft authenticator

### ISSUE THREAD

**Issue by rashmi29** [yeojz/otplib#315]
**Describe the bug**
6 digit number generated using authenticator.generate() is not working with microsoft authenticator. After entering this token, it is showing "You didn't enter the expected verification code.Please try again."

.check and .verify is returning true but 6 digit code is not working while login.

**Expected behavior**
Six digit code should work and I should be able to my application.

**Details (please provide any relevant information):**
- otplib version: 12.0.1
- os: Windows 10
- browser: Chrome
- node / yarn: node
- frameworks (if any): jasmine

**Comment by Chris927** [comment]
It worked for me, see [my gist](https://gist.github.com/Chris927/7d2532360b409e7ec9e5b6fa6414b970).

Hope this helps.

**Comment by yeojz** [comment]
Thanks @Chris927 
Are you still encountering the issue?

**Comment by Chris927** [comment]
> Thanks @Chris927
> Are you still encountering the issue?

@yeojz  As mentioned above, if I use the approach in my gist, it works fine. @rashmi29, can you comment?

**Comment by rashmi29** [comment]
This can be closed. Thanks @Chris927  @yeojz .

**Comment by TranBaVinhSon** [comment]
@rashmi29 How can you solve your problem ?
