### ISSUE TITLE
Time Validity

### ISSUE THREAD

**Issue by arvindr21** [yeojz/otplib#4]
Hello @yeojz 

Thanks for module. 

I am presently using the `totp` scheme for generating OTPs, Wanted to know what is the validity of the OTP. As in how long the OTP will be valid. There are times when the SMS service is busy and take a few seconds longer. In that case the OTP from `totp` scheme is invalid and the user needs to generate a new one. So, is there a way I can increase this time out by a few seconds (this is a silly question)? 

I am aware that I can use `hotp` for perpetually valid token but wanted to stick with `totp` for its security.

Any help is appreciated.

Thanks,
Arvind.

**Comment by mycloudyhopes** [comment]
Hey, did you find a way to do it.. I too want to increase the validity

**Comment by arvindr21** [comment]
No I couldn't. Ended up using https://www.npmjs.com/package/speakeasy
module.

On Dec 4, 2016 22:56, "mycloudyhopes" <notifications@github.com> wrote:

Hey, did you find a way to do it.. I too want to increase the validity

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yeojz/otplib/issues/4#issuecomment-264717355>, or mute
the thread

**Comment by yeojz** [comment]
Totally missed this. 

@mycloudyhopes 
Currently the library does not expose the time interval.

Am a little stretched at work and couldn't give much attention here. I can probably set some time aside over the coming weekend to take a look at it.

Alternatively, you can also go with speakeasy which @arvindr21 suggested, which seems much more recent. Thanks @arvindr21

**Comment by mycloudyhopes** [comment]
Thanks @arvindr21 & @yeojz 
Your responses really helped me.

**Comment by AmreeshTyagi** [comment]
@mycloudyhopes @arvindr21 @yeojz As far as I know, this library is very good & also provides time interval for totp (not sure about hotp). I am already using it.

If you look into the code of totp [https://github.com/yeojz/otplib/blob/master/src/classes/TOTP.js](url) , you can see step propery, which you can pass during initialization like
`var lib = require('otplib');`
`var totp = lib.totp;`
`totp.options({ step: 120});` in seconds. Your generated token will be expired after 120 seconds.

@yeojz Please let me know, if I am missing something.

**Comment by yeojz** [comment]
@AmreeshTyagi @mycloudyhopes @arvindr21 

Will be doing a clean up of this library + updating all outdated dependencies + refactoring. #5 
Shall do a refresh of documentations as well since it seems to be lacking that even I myself missed it.
If there are any more concerns, let me know and I'll take note to include into documentations.

Thanks!
