### ISSUE TITLE
How to generate a secret based on own data?

### ISSUE THREAD

**Issue by thEpisode** [yeojz/otplib#45]
Hi, 

First, this library is awesome. I want to know how to create my own seed based on personal data, like an id of database or another info, I'm checking otplib.authenticator.generateSecret but their only has one parameter to generate with length. Exist any way?

**Comment by yeojz** [comment]
@thEpisode you can just use your own function to generate your secret. As long as you pass the generated secret string to `Authenticator.utils.encodeKey(YOUR_GENERATED_SECRET_STRING)`, it should decode correctly.

**Comment by thEpisode** [comment]
Nice, thanks, has any lenght restriction? or I need to pass a hash?

**Comment by thEpisode** [comment]
Authenticator.utils.encodeKey hasn't any length restrictions!! 👏👏👏👏
