### ISSUE TITLE
safari10 caught Cannot declare a let variable twice: 'n

### ISSUE THREAD

**Issue by navigator117** [yeojz/otplib#46]
seem's cause by webpack uglify plugin

**Comment by yeojz** [comment]
Hmm.. I don't have any laptops with Safari 10 running, and I cannot verify this at the moment.
Safari 11 seems fine. 

Probably will have to tweak `babel` to take that into account.

**Comment by navigator117** [comment]
fixed by add below section to scripts/webpack.config.js   
new UglifyJsPlugin({
            uglifyOptions: {
                safari10: true
            }
        })
