### ISSUE TITLE
TypeError: otplib_1.otplib is undefined

### ISSUE THREAD

**Issue by Spirit-act** [yeojz/otplib#47]
Hello,

I'm new in angular and run into this Error: TypeError: otplib_1.otplib is undefined

I have install the package
```bash
npm install otplib --save
```
I have also tryed
```bash
npm install otplib@next --save
```
---

I have it included with following code:
```
import { otplib } from "otplib";
```

At this point "vs code" tells me that there is a definition file (*.d.ts) missing.

---

I try to use the Authenenticator class:
```
createSecret()
  {
    let authenticator = new otplib.Authenenticator();
    authenticator.options = { crypto }
    const secret = authenticator.generateSecret();
    return secret;
  }
```

I have alseo tryed:
```
createSecret()
  {
    const secret = otplib.authenticator.generateSecret();
    return secret;
  }
```

My major question is, what do I wrong?
I try to follow your instructions at [https://yeojz.github.io/otplib/docs/](https://yeojz.github.io/otplib/docs/) but it doen't work.

Please, give me an instruction that it work.

**Comment by yeojz** [comment]
That's not really enough to go by. 
More details would be helpful. eg: are you using babel, node version etc.

From an online repl, the library doesn't seem to have any issues.
try it out: https://repl.it/repls/GlitteringEmotionalUpgrades

**Comment by Spirit-act** [comment]
Hi @yeojz,

### Details:

| module | verision |
| --- | --- |
| nodejs | v6.11.4 |
| angular cli | 1.6.5 |
| webpack | 3.10.0 |

---

### The Project
I have a login Component with a service and a module.

- The standard route, routs to "/dashboard".
- The auth.guard.ts looks for a specific variable if the variable is not set it routs to "/login".
- After you enter your credentials into the Login form, you will be redirected to "/2fa".
- The 2FA is a separate module. It asks the server if the user has a 2fa already set. If not the user gets the qrcode.

---

### My Functions

###### Import the Modules
```
import qrcode from "qrcode";
import otplib from 'otplib';
```
###### Create QRCode Function
```
createQRCode(party:Party)
  {
    let secret  = party.secret_key;
    let imgUrl;
    if (secret == '') {
      secret = this.createSecret();
    }
    let user = party.login
    const otpauth = otplib.authenticator.keyuri(user, 'Webclient', secret);

    qrcode.toDataURL(otpauth, (err, imgUrl) => {
      if (err) {
        console.log('Error with QR');
        return;
      }
      this.imgCache = imgUrl;
    });
  }
```

###### Create Secret Function
```
createSecret()
  {
    const secret = otplib.authenticator.generateSecret();
    return secret;
  }
```

###### Verify Function
```
check2fa(party:Party){
    if (localStorage.getItem('isHalfLoggedin')) {
      if (otplib.authenticator.check(this.code, party.secret_key)) {
        localStorage.removeItem('isHalfLoggedin');
        localStorage.setItem('isLoggedin','true');
      } else {
        this.ErrorMessage = 'Token is invalid';
        setTimeout(() => {this.ErrorMessage = null;},5000);
      }
    }
    this.router.navigate(['/dashboard']);
  }
```

Maybe this informations can help you to understand my Problem.

Thx for your help

Best regards
Spirit-act

**Comment by yeojz** [comment]
At a glance, I can't really conclude on the issue.. A suspicion is that the `import` statements ain't being compiled properly. Maybe you can try using `const otplib = require('otplib')` instead?

I'll need to dig futher over the weekend. I haven't really used the angular-cli tooling, so unsure what's provided out-of-the-box

**Comment by yeojz** [comment]
@Spirit-act 
I've tested it out with an angular-cli new project. It would seem that it is actually mainly `angular` and `typescript` that is causing issues, and not specific to the library. There are 2 issues when using with angular 4 / typescript. 

1. crypto imports seems to be dropped
2. typescript transforms default `module.exports` into named exports.

A quick fix for this is instead of doing:

```js
import otplib from 'otplib'

otplib.authenticator.generateSecret();
```

use the browser build included instead:

```js
import { authenticator } from 'otplib/otplib-browser';

authenticator.generateSecret();
```

Let me know if that works for you.

For now, I will not be making any changes as it is not apparent that it is a issue with the library itself.

Thanks

---

The following are modified files from a default `@angular/cli` generate output that I used for tryouts.

__app.component.ts__

```js
import { Component } from '@angular/core';
import { authenticator } from 'otplib/otplib-browser';
import { toDataURL } from 'qrcode';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'otplib test';
  secret = '';
  imageURL = '';

  constructor() {
    console.log(authenticator);
    this.secret = this.createSecret();
    this.createQRCode();
  }

  createSecret() {
    return authenticator.generateSecret();
  }

  createQRCode() {
    const otpauth = authenticator.keyuri('test', 'Webclient', this.secret);

    toDataURL(otpauth, (err, imgUrl) => {
      if (err) {
        console.log('Error with QR');
        return;
      }
      this.imageURL = imgUrl;
    });
  }
}

```

__app.component.html__

```html
<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
</div>
<div style="text-align:center">
  <table>
    <tbody>
        <tr>
          <th>Secret</th>
          <td>{{ secret }}</td>
        </tr>
        <tr>
            <th>imageURL</th>
            <td><img src="{{ imageURL }}" alt="" /></td>
          </tr>
    </tbody>
  </table>
</div>

```

**Comment by Spirit-act** [comment]
@yeojz 

I will try your changes as soon as possible but the whole app is build in an company environment and in the next 3 weeks, I am not able to access this environment. 

So sry for the delay.

**Comment by Spirit-act** [comment]
@yeojz 

Your answer was the solution. The QR Code works and the secret key generation works too.
I'm working on the verification right now.
Thx for your help.
