### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by miguelmota** [yeojz/otplib#48]
I scanned the code on the demo page but verification fails when I enter the code from my Google Authenticator app. 

The code displayed on the demo page (and what otplib is verifying against) is always 1 code before the current code on my phone.

Basically after the time expires, I get a new code on my phone but the code displayed on the demo page is the previous code that was displayed on my phone. 

So verification doesn't work.

I've tested with both iPhone and Android latest versions of Google Authenticator and both didn't verify. 

Not sure what to do. 

Any help is appreciated.

Thanks

**Comment by miguelmota** [comment]
Ended up using the [speakeasy](https://github.com/speakeasyjs/speakeasy) module for 2FA which works a lot better.

**Comment by yeojz** [comment]
The syncs are base on your clock. If there is a time difference the code will not validate. The examples are set to strict times with no grace periods.

**Comment by miguelmota** [comment]
@yeojz thanks for clarifying!
