### ISSUE TITLE
not able to build my app

### ISSUE THREAD

**Issue by skhekare** [yeojz/otplib#88]
getting following error 

ERROR in node_modules/otplib/index.d.ts(6,67): error TS2304: Cannot find name 'Buffer'.

**Comment by yeojz** [comment]
@skhekare  

You need to have the typedef for node as well. 
If you haven't, do run `npm install @types/node`.

**Comment by mattheuspirovani** [comment]
Same error...

**Comment by marcosgouvea** [comment]
@skhekare  @mattheuspirovani @yeojz  i changed the "Buffer" to "Any" and it worked

**Comment by yeojz** [comment]
@marcosgouvea did you try `npm install @types/node`before that?

**Comment by marcosgouvea** [comment]
yea that was the problem, whem i installed  @types/node everything worked.

**Comment by yeojz** [comment]
Closing this issue as it's verified by marcosgouvea that library is working.

However, PR'ed to moved the instruction on how to use with typescript within the readme to it's own section to make it more prominent.
